### ISSUE TITLE
isotropic_elasticity_tensor over written 

### ISSUE THREAD

**Issue by TeroFrondelius** [JuliaFEM/Materials.jl#55]
`WARNING: Method definition isotropic_elasticity_tensor(Any, Any) in module Materials at C:\Users\travis\.julia\packages\Materials\mSWeT\src\idealplastic.jl:5 overwritten at C:\Users\travis\.julia\packages\Materials\mSWeT\src\chaboche.jl:5.`

**Comment by ahojukka5** [comment]
In `chaboche.jl`:

```julia
function isotropic_elasticity_tensor(lambda, mu) 
    delta(i,j) = i==j ? 1.0 : 0.0 
    g(i,j,k,l) = lambda*delta(i,j)*delta(k,l) + mu*(delta(i,k)*delta(j,l)+delta(i,l)*delta(j,k))
    jacobian = SymmetricTensor{4, 3, Float64}(g)
    return jacobian
end
```

in `idealplastic.jl`:

```julia
function isotropic_elasticity_tensor(lambda, mu) 
    delta(i,j) = i==j ? 1.0 : 0.0 
    g(i,j,k,l) = lambda*delta(i,j)*delta(k,l) + mu*(delta(i,k)*delta(j,l)+delta(i,l)*delta(j,k))
    jacobian = SymmetricTensor{4, 3, Float64}(g)
    return jacobian
end
```

It looks same for me. Maybe we should have something like `common.jl` where we define these kinds of functions?
