### ISSUE TITLE
Upgrade to work with Julia v1

### ISSUE THREAD

**Issue by ahojukka5** [JuliaFEM/Materials.jl#6]

**Comment by ahojukka5** [comment]
I made a temporary hack (see PR #7) that old code is included in `olli.jl` which is not included in `Materials.jl` to make the package work in v1.

**Comment by ovainola** [comment]
I guess this can be closed, since current master work on v1.0.0?

**Comment by ahojukka5** [comment]
Well if you have any old material models they should anyway to make work with a new material framework. Maybe copy-pasting the old code and doing pull requests is an easier way to go?

**Comment by ovainola** [comment]
agree, with the new interface you developed during the hackaton, old codes are obsole and should be integrated using PRs
